version: '3.8'

services:
  app:
    build: .
    container_name: zhora_bot
    restart: always
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
    env_file:
      - .env

  postgres:
    image: postgres:15
    container_name: zhora_db
    restart: always
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "${DB_PORT}:5432"
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "${DB_USER}" ]
      interval: 3s
      timeout: 2s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: zhora_redis
    restart: always
    volumes:
      - redis_data:/data
    ports:
      - "${REDIS_PORT}:6379"

volumes:
  postgres_data:
  redis_data:
